- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
     - name: Copy WAR file to Tomcat
       copy: 
         src: "/var/snap/jenkins/4844/workspace/MvnAnsWeb/target/MvnAnsWeb.war"
         dest: "/opt/tomcat/webapps/MvnAnsWeb.war"
         remote-src: no
         
     - name: Restart Tomcat
       systemd:
         name: tomcat
         state: restarted
         
         
